name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS environment
        uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          
      - name: Install dependencies
        run: yarn
      - name: Run build
        run: yarn build
        
      - name: SSH copy Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          pasword: ${{ secrets.SSH_PASS }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ".,!node_modules"
          target: "~/app/vieweg/backend"
        
      - name: SSH Install dependencies and restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            yarn
            pm2 restart API_VIEWEG
